api = "0.4"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-engine"
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Node Engine Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "14.*.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:12.22.0:*:*:*:*:*:*:*"
    deprecation_date = "2022-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "630dff2d02305064c223464e94b34451fc3cf7b59e73f8d68afa8b622959087d"
    source = "https://nodejs.org/dist/v12.22.0/node-v12.22.0.tar.gz"
    source_sha256 = "a65d108d824e956de0ab7c3e7f6763c70f6f5b85636dc4ee16404e5881b7d723"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v12.22.0_linux_x64_bionic_630dff2d.tgz"
    version = "12.22.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:12.22.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "d1c52f1c81c24185dc2e993dfcd18c7c812a56c93622cce37c49c07111df6c4c"
    source = "https://nodejs.org/dist/v12.22.1/node-v12.22.1.tar.gz"
    source_sha256 = "6023f1f8f03f9780c75e6eca9d372b8411a83757c0389c51baee1c7242afd702"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v12.22.1_linux_x64_bionic_d1c52f1c.tgz"
    version = "12.22.1"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:14.16.1:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "858aff7f4cf75e8c7c1100b2794488eb3d10ca19975b8cb3f2e09b5de82ed4e3"
    source = "https://nodejs.org/dist/v14.16.1/node-v14.16.1.tar.gz"
    source_sha256 = "5f5080427abddde7f22fd2ba77cd2b8a1f86253277a1eec54bc98a202728ce80"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v14.16.1_linux_x64_bionic_858aff7f.tgz"
    version = "14.16.1"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:14.17.0:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "36155ab8a024103fc752e35c74ed4f65490f0303c6e824a6fd0b0c7f84591e0b"
    source = "https://nodejs.org/dist/v14.17.0/node-v14.17.0.tar.gz"
    source_sha256 = "6114e82d3256136dc85a509d835442fbdf2f8430dcd8bfa7c304097344d06fb7"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v14.17.0_linux_x64_bionic_36155ab8.tgz"
    version = "14.17.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:15.13.0:*:*:*:*:*:*:*"
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "1ddd140fa72ed2b66f666231da512f9e593d4ea99a0b80e011a72056f5eba9ef"
    source = "https://nodejs.org/dist/v15.13.0/node-v15.13.0.tar.gz"
    source_sha256 = "96926e5b8f2f3ea805596448f01b16115882f3a594e2e999dc7349f80b3ec1f8"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v15.13.0_linux_x64_bionic_1ddd140f.tgz"
    version = "15.13.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:15.14.0:*:*:*:*:*:*:*"
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "e04f8e8c133af229f737d9059ef25e9b2a490dd0fdabb5367f00ef5c8cadf71e"
    source = "https://nodejs.org/dist/v15.14.0/node-v15.14.0.tar.gz"
    source_sha256 = "f3a35c1b29b58846575085fdee7774d78b75ff4cf1e52572afce7f38685b159a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v15.14.0_linux_x64_bionic_e04f8e8c.tgz"
    version = "15.14.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:16.2.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "873869dee81f3c474b9bb307dd920e2400b363b3f8d584aa538c70a9f567f6fa"
    source = "https://nodejs.org/dist/v16.2.0/node-v16.2.0.tar.gz"
    source_sha256 = "5d093d6b203159aa3288a1d51495d2faf11550f0755d04015161a529a065b12a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v16.2.0_linux_x64_bionic_873869de.tgz"
    version = "16.2.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:16.3.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "584a04d08cda20b7e20e33c097cd3aa6b9e4abcbb74a59c88689f646f0282f94"
    source = "https://nodejs.org/dist/v16.3.0/node-v16.3.0.tar.gz"
    source_sha256 = "11d00034a9864660eadf9835d09de2bed97b245093626705d8917897d8f36704"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v16.3.0_linux_x64_bionic_584a04d0.tgz"
    version = "16.3.0"

  [[metadata.dependency-constraints]]
    constraint = "12.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "14.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "15.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "16.*"
    id = "node"
    patches = 2

  [[metadata.dependency_deprecation_dates]]
    date = "2022-04-01T00:00:00Z"
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = "2023-04-30T00:00:00Z"
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "14.x.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
