api = "0.2"

[buildpack]
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Node Engine Buildpack"
  homepage = "https://github.com/paketo-buildpacks/node-engine"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "14.*.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "e13e1ce3c0991499f102cc28768daef06eea8e6f0753bd911dc11546f0226852"
    source = "https://nodejs.org/dist/v10.23.0/node-v10.23.0.tar.gz"
    source_sha256 = "d93041d1d1e75cef6c562c29b63333b2f39a16de3cb0310b695130cea2ae7f27"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_10.23.0_linux_x64_cflinuxfs3_e13e1ce3.tgz"
    version = "10.23.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "683b8159feb77d084453aae4ecdb887ba0484a71ce999096b13d2527ea35b15c"
    source = "https://nodejs.org/dist/v10.23.1/node-v10.23.1.tar.gz"
    source_sha256 = "a5348b5dfdbe32e0be2837576e66ac285a59907e11e5439fbcda25e70f52550d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_10.23.1_linux_x64_cflinuxfs3_683b8159.tgz"
    version = "10.23.1"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "0b7da2ac2c1b6f3fb97e6d81926f0e52754a3b47e93408205fa1bb39133ed069"
    source = "https://nodejs.org/dist/v12.20.0/node-v12.20.0.tar.gz"
    source_sha256 = "b91065ebe60981faa0e1f0a37d1788154141c710bb0521635a900895a7ce8dd8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.20.0_linux_x64_cflinuxfs3_0b7da2ac.tgz"
    version = "12.20.0"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "7fde300a90f69e2c42e88e7bc42e1259b9f715567f3685f3a62000818d8f670e"
    source = "https://nodejs.org/dist/v12.20.1/node-v12.20.1.tar.gz"
    source_sha256 = "5318a5db1484050430371b77dece281a5b078a14e6962e105aa5790bdb3c3bed"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.20.1_linux_x64_cflinuxfs3_7fde300a.tgz"
    version = "12.20.1"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "90f2238580c9f2d6d0695526e20c689e3e8310a94d95725c437eb5af65b8efc6"
    source = "https://nodejs.org/dist/v14.15.2/node-v14.15.2.tar.gz"
    source_sha256 = "f3a6558bd4991f6bb2b4c9d1fc8454518003cebfc732a82aab15dc99069952de"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.15.2_linux_x64_cflinuxfs3_90f22385.tgz"
    version = "14.15.2"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "8ee83120dffd95aa5ef8d26494fdf8e37f93173d58f3528c6a853296d363561a"
    source = "https://nodejs.org/dist/v14.15.3/node-v14.15.3.tar.gz"
    source_sha256 = "d23a5c354f1c30278477e4e8d1ecb4c12660a4d1ba2476feeed9434e6bf5b96e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.15.3_linux_x64_cflinuxfs3_8ee83120.tgz"
    version = "14.15.3"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "d5a2bb2f6e647fd91f06f27dfe26a93d5aa29f3f40b5dc5a01e46a7114848cf6"
    source = "https://nodejs.org/dist/v15.5.0/node-v15.5.0.tar.gz"
    source_sha256 = "a4f10a2e67dc99ed64c297be988fbe37f8a62f8fb8ff880f121f8be4e30df3d1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.5.0_linux_x64_cflinuxfs3_d5a2bb2f.tgz"
    version = "15.5.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "35ac36cefae753d0c9e0babd20c7ebd8ff036b177c50f3211273319725a3d557"
    source = "https://nodejs.org/dist/v15.5.1/node-v15.5.1.tar.gz"
    source_sha256 = "9730d3099c051bd8733b3e6d62c54ba9b2d82ec40e6c65ee966ba3f346ff4157"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.5.1_linux_x64_cflinuxfs3_35ac36ce.tgz"
    version = "15.5.1"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "10.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-04-30T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "14.x.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
