api = "0.4"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-engine"
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Node Engine Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "14.*.*"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:12.22.1:*:*:*:*:*:*:*"
    deprecation_date = "2022-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "d1c52f1c81c24185dc2e993dfcd18c7c812a56c93622cce37c49c07111df6c4c"
    source = "https://nodejs.org/dist/v12.22.1/node-v12.22.1.tar.gz"
    source_sha256 = "6023f1f8f03f9780c75e6eca9d372b8411a83757c0389c51baee1c7242afd702"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v12.22.1_linux_x64_bionic_d1c52f1c.tgz"
    version = "12.22.1"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:12.22.2:*:*:*:*:*:*:*"
    deprecation_date = "2022-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "72afae595cd1353ad21544d4328d9b5d5651ff6044b29dc1e26ff7436462762c"
    source = "https://nodejs.org/dist/v12.22.2/node-v12.22.2.tar.gz"
    source_sha256 = "210a550c47056f29537e1b5b73cb78a88c44609c3b92aa003cf7862d3904ef99"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v12.22.2_linux_x64_bionic_72afae59.tgz"
    version = "12.22.2"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:14.17.1:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "38dd615ad9baa4d2433ae48911ce1306042337539d2d6916e31442a598e44424"
    source = "https://nodejs.org/dist/v14.17.1/node-v14.17.1.tar.gz"
    source_sha256 = "f85297faa15529cf134e9cfd395371fea62e092c3fe2127f2b0fdf8504905cee"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v14.17.1_linux_x64_bionic_38dd615a.tgz"
    version = "14.17.1"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:14.17.2:*:*:*:*:*:*:*"
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "83d999aae0a9ce23b2c6dda3a22c3749272968cb7db2ed80d4279643d50df4c6"
    source = "https://nodejs.org/dist/v14.17.2/node-v14.17.2.tar.gz"
    source_sha256 = "03bea54a68c6fa8b520c273a1dc80f2fdbf80ddc9c303200d2eeaf25bd7e62fa"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v14.17.2_linux_x64_bionic_83d999aa.tgz"
    version = "14.17.2"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:15.13.0:*:*:*:*:*:*:*"
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "1ddd140fa72ed2b66f666231da512f9e593d4ea99a0b80e011a72056f5eba9ef"
    source = "https://nodejs.org/dist/v15.13.0/node-v15.13.0.tar.gz"
    source_sha256 = "96926e5b8f2f3ea805596448f01b16115882f3a594e2e999dc7349f80b3ec1f8"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v15.13.0_linux_x64_bionic_1ddd140f.tgz"
    version = "15.13.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:15.14.0:*:*:*:*:*:*:*"
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "e04f8e8c133af229f737d9059ef25e9b2a490dd0fdabb5367f00ef5c8cadf71e"
    source = "https://nodejs.org/dist/v15.14.0/node-v15.14.0.tar.gz"
    source_sha256 = "f3a35c1b29b58846575085fdee7774d78b75ff4cf1e52572afce7f38685b159a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v15.14.0_linux_x64_bionic_e04f8e8c.tgz"
    version = "15.14.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:16.3.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "584a04d08cda20b7e20e33c097cd3aa6b9e4abcbb74a59c88689f646f0282f94"
    source = "https://nodejs.org/dist/v16.3.0/node-v16.3.0.tar.gz"
    source_sha256 = "11d00034a9864660eadf9835d09de2bed97b245093626705d8917897d8f36704"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v16.3.0_linux_x64_bionic_584a04d0.tgz"
    version = "16.3.0"

  [[metadata.dependencies]]
    cpe = "cpe:2.3:a:nodejs:node.js:16.4.0:*:*:*:*:*:*:*"
    deprecation_date = "2024-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "2bd4f257148a97ac452281194f5aa199c367b2ca3abf7227db543daf6cbebc61"
    source = "https://nodejs.org/dist/v16.4.0/node-v16.4.0.tar.gz"
    source_sha256 = "37e526b494a0ae53d2205421b93cc3d6fa2d9f4d8349891814a23e69d59a6d8d"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://deps.paketo.io/node/node_v16.4.0_linux_x64_bionic_2bd4f257.tgz"
    version = "16.4.0"

  [[metadata.dependency-constraints]]
    constraint = "12.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "14.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "15.*"
    id = "node"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "16.*"
    id = "node"
    patches = 2

  [[metadata.dependency_deprecation_dates]]
    date = "2022-04-01T00:00:00Z"
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = "2023-04-30T00:00:00Z"
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "14.x.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
