api = "0.2"

[buildpack]
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Node Engine Buildpack"
  homepage = "https://github.com/paketo-buildpacks/node-engine"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "10.x"

  [[metadata.dependencies]]
    deprecation_date = "2021-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "d84ec1b77780923f2d0d30f9155dfcba411c67ae53548684a140b2ec982fdeba"
    source = "https://nodejs.org/dist/v10.22.1/node-v10.22.1.tar.gz"
    source_sha256 = "d0b49dd96ac70e99240458863efe09ae5bb1138c0ff582295f882c1482708172"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_10.22.1_linux_x64_cflinuxfs3_d84ec1b7.tgz"
    version = "10.22.1"

  [[metadata.dependencies]]
    deprecation_date = "2021-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "e13e1ce3c0991499f102cc28768daef06eea8e6f0753bd911dc11546f0226852"
    source = "https://nodejs.org/dist/v10.23.0/node-v10.23.0.tar.gz"
    source_sha256 = "d93041d1d1e75cef6c562c29b63333b2f39a16de3cb0310b695130cea2ae7f27"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_10.23.0_linux_x64_cflinuxfs3_e13e1ce3.tgz"
    version = "10.23.0"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "2c0046f5d0bdccf7738ba6b5e3f1084a866ff4a92c5a3f3e820b3fd8e2101fbc"
    source = "https://nodejs.org/dist/v12.18.4/node-v12.18.4.tar.gz"
    source_sha256 = "a802d87e579e46fc52771ed6f2667048320caca867be3276f4c4f1bbb41389c3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.18.4_linux_x64_cflinuxfs3_2c0046f5.tgz"
    version = "12.18.4"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "03ab83e564d3cfc824e6cb1c8f167d063056f907adfe90a4d7ff7033c7186e99"
    source = "https://nodejs.org/dist/v12.19.0/node-v12.19.0.tar.gz"
    source_sha256 = "1279e49be60d92cf4c1a48c9d92397db4e9284a100bc47689ce7924686bbddd1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.19.0_linux_x64_cflinuxfs3_03ab83e5.tgz"
    version = "12.19.0"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "f6fd410294980c039f2280c3db94793d899921ae5a08f9e1aa79cf5eb55384b4"
    source = "https://nodejs.org/dist/v14.13.1/node-v14.13.1.tar.gz"
    source_sha256 = "f0080d3284ea1585e255a3f459ce151e8106a33f4ce8bed0da15ff99c6a082a5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.13.1_linux_x64_cflinuxfs3_f6fd4102.tgz"
    version = "14.13.1"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "4ac6c1ed28061e978d97a6bf5e440ac218ab55a89d8df39b73d39dba087b910a"
    source = "https://nodejs.org/dist/v14.14.0/node-v14.14.0.tar.gz"
    source_sha256 = "afb0b401d62d9fcfc68258f50d0bf042998d349ce9c1d7a2d45dd87870b3aab7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.14.0_linux_x64_cflinuxfs3_4ac6c1ed.tgz"
    version = "14.14.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "d87f6e4ece97c37b878a8e2af065d3aa8a61933ec3150989fbddf2d25642c8ee"
    source = "https://nodejs.org/dist/v15.0.0/node-v15.0.0.tar.gz"
    source_sha256 = "72f6234594877ab212c43a76f2f5b05d409d7c025e0eb36d675d9acfd0d3f2d8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.0.0_linux_x64_cflinuxfs3_d87f6e4e.tgz"
    version = "15.0.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "c2d64914b8d343ab053740b7225d86c8f153838caf5965f273cf02fae2abdf4b"
    source = "https://nodejs.org/dist/v15.0.1/node-v15.0.1.tar.gz"
    source_sha256 = "b9a00a4847863914ffe7751c2d81b67cb96a8f958cbc692f988c8c78db14ebec"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.0.1_linux_x64_cflinuxfs3_c2d64914.tgz"
    version = "15.0.1"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "10.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-04-30T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "14.x.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
