api = "0.4"

[buildpack]
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Node Engine Buildpack"
  homepage = "https://github.com/paketo-buildpacks/node-engine"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "14.*.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "82e375d32ac721deea1a3a917d185e601138f64ba2e708f5a83f36407a438410"
    source = "https://nodejs.org/dist/v10.23.3/node-v10.23.3.tar.gz"
    source_sha256 = "517db39eefccb03cb9ec1de67ddc917be943a755b290bff309b2e4b1bd78ffaf"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_10.23.3_linux_x64_cflinuxfs3_82e375d3.tgz"
    version = "10.23.3"

  [[metadata.dependencies]]
    deprecation_date = "2021-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "db472e2969345e4e8bd58f42342518a327c97c99e80bec7e4c9d2fed3bb31bb1"
    source = "https://nodejs.org/dist/v10.24.0/node-v10.24.0.tar.gz"
    source_sha256 = "c8d0a56279be77a9033b5f89603c6c491060a661c607fbf82bbe931ca662996e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_10.24.0_linux_x64_cflinuxfs3_db472e29.tgz"
    version = "10.24.0"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "a91c3e62db6255189c9eb3ecd7b69665a3ffc4b531f3cb36b2f6e3a350e0c454"
    source = "https://nodejs.org/dist/v12.21.0/node-v12.21.0.tar.gz"
    source_sha256 = "36e862555bebc04b13f7afebf4472c4dd7ebf4c891f9d6746ec545a4f099d05e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.21.0_linux_x64_cflinuxfs3_a91c3e62.tgz"
    version = "12.21.0"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "e989015105b6b7f2e8e4b48b5dbec4be5dce5b0078cf52a34b78551c50ad1829"
    source = "https://nodejs.org/dist/v12.22.0/node-v12.22.0.tar.gz"
    source_sha256 = "a65d108d824e956de0ab7c3e7f6763c70f6f5b85636dc4ee16404e5881b7d723"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.22.0_linux_x64_cflinuxfs3_e9890151.tgz"
    version = "12.22.0"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "63a8a4d43c325856c2e4673b30dc44e8ea973a5a4f21ed616fa7ee2c31cfe7f4"
    source = "https://nodejs.org/dist/v14.15.5/node-v14.15.5.tar.gz"
    source_sha256 = "043f39bb43ecaca699a21a8bd65d064ef53b48bf2cc6acaddb5ee0f4227e4d2a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.15.5_linux_x64_cflinuxfs3_63a8a4d4.tgz"
    version = "14.15.5"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "a194ec213d96599f96ca3455e873580d3441e407787e17fae6d6d0fa8b919f3b"
    source = "https://nodejs.org/dist/v14.16.0/node-v14.16.0.tar.gz"
    source_sha256 = "f6b904b06951de4c52089dd4456155d853e835b0dc4640f75458c6eb49f9e8ce"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.16.0_linux_x64_cflinuxfs3_a194ec21.tgz"
    version = "14.16.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "b68f13900322d1a6013ee6556e4415e872f93ebc4b3802c32071555d76ef0107"
    source = "https://nodejs.org/dist/v15.12.0/node-v15.12.0.tar.gz"
    source_sha256 = "cfb13ad6443e9e08d2c37468e57d2d79b91c5372e9d9d3f03756a0e31d984497"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.12.0_linux_x64_cflinuxfs3_b68f1390.tgz"
    version = "15.12.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "d240c2853f19e57cfacccf0f1fd7a6c787f519bd6e7507fd38b248d8d71f4ef2"
    source = "https://nodejs.org/dist/v15.13.0/node-v15.13.0.tar.gz"
    source_sha256 = "96926e5b8f2f3ea805596448f01b16115882f3a594e2e999dc7349f80b3ec1f8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.13.0_linux_x64_cflinuxfs3_d240c285.tgz"
    version = "15.13.0"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "10.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-04-30T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "14.x.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
