api = "0.2"

[buildpack]
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Node Engine Buildpack"
  homepage = "https://github.com/paketo-buildpacks/node-engine"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "14.*.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "d84ec1b77780923f2d0d30f9155dfcba411c67ae53548684a140b2ec982fdeba"
    source = "https://nodejs.org/dist/v10.22.1/node-v10.22.1.tar.gz"
    source_sha256 = "d0b49dd96ac70e99240458863efe09ae5bb1138c0ff582295f882c1482708172"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_10.22.1_linux_x64_cflinuxfs3_d84ec1b7.tgz"
    version = "10.22.1"

  [[metadata.dependencies]]
    deprecation_date = "2021-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "e13e1ce3c0991499f102cc28768daef06eea8e6f0753bd911dc11546f0226852"
    source = "https://nodejs.org/dist/v10.23.0/node-v10.23.0.tar.gz"
    source_sha256 = "d93041d1d1e75cef6c562c29b63333b2f39a16de3cb0310b695130cea2ae7f27"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_10.23.0_linux_x64_cflinuxfs3_e13e1ce3.tgz"
    version = "10.23.0"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "03ab83e564d3cfc824e6cb1c8f167d063056f907adfe90a4d7ff7033c7186e99"
    source = "https://nodejs.org/dist/v12.19.0/node-v12.19.0.tar.gz"
    source_sha256 = "1279e49be60d92cf4c1a48c9d92397db4e9284a100bc47689ce7924686bbddd1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.19.0_linux_x64_cflinuxfs3_03ab83e5.tgz"
    version = "12.19.0"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "117259832364fb8fa729e0877478e132e2d55d72fdd089b9099ee507770014ab"
    source = "https://nodejs.org/dist/v12.19.1/node-v12.19.1.tar.gz"
    source_sha256 = "83c36a4b8e9fd0111af8338657395c2fc05b2c34ecfc2618f6347fc284949889"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.19.1_linux_x64_cflinuxfs3_11725983.tgz"
    version = "12.19.1"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "4ac6c1ed28061e978d97a6bf5e440ac218ab55a89d8df39b73d39dba087b910a"
    source = "https://nodejs.org/dist/v14.14.0/node-v14.14.0.tar.gz"
    source_sha256 = "afb0b401d62d9fcfc68258f50d0bf042998d349ce9c1d7a2d45dd87870b3aab7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.14.0_linux_x64_cflinuxfs3_4ac6c1ed.tgz"
    version = "14.14.0"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "5e4e7f1072e08ef589d3807622ce7574ffba6872e8a9096141cff9c8921bc2e1"
    source = "https://nodejs.org/dist/v14.15.0/node-v14.15.0.tar.gz"
    source_sha256 = "5f9529e0a42985d5a81620635ab2541e3553daede42903d1b3176f808d46411c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.15.0_linux_x64_cflinuxfs3_5e4e7f10.tgz"
    version = "14.15.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "10d2b58d3ffc7194f182fc80b9710b6ebf3c575aa3c07174244da1d3ccbc6986"
    source = "https://nodejs.org/dist/v15.1.0/node-v15.1.0.tar.gz"
    source_sha256 = "b44e4ac58b0660909e41390c3380a14669480c3f947d078d78d356ce3d1ba4bc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.1.0_linux_x64_cflinuxfs3_10d2b58d.tgz"
    version = "15.1.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "5973c9dafd8e2d31ba6f2ebe558b3315a58a2912090e15b0b7f3a09754ed1799"
    source = "https://nodejs.org/dist/v15.2.0/node-v15.2.0.tar.gz"
    source_sha256 = "a4c807cebda11a5f9ec50f340b0a916fa64423864c553c6f56da4404ece7a384"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.2.0_linux_x64_cflinuxfs3_5973c9da.tgz"
    version = "15.2.0"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "10.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-04-30T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "14.x.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
