api = "0.4"

[buildpack]
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Node Engine Buildpack"
  homepage = "https://github.com/paketo-buildpacks/node-engine"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "14.*.*"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "e989015105b6b7f2e8e4b48b5dbec4be5dce5b0078cf52a34b78551c50ad1829"
    source = "https://nodejs.org/dist/v12.22.0/node-v12.22.0.tar.gz"
    source_sha256 = "a65d108d824e956de0ab7c3e7f6763c70f6f5b85636dc4ee16404e5881b7d723"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.22.0_linux_x64_cflinuxfs3_e9890151.tgz"
    version = "12.22.0"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "8e413a41da4eb2689cd8c5100ed6ab738c4a04ec3943c012ba6a8dec489e5ce1"
    source = "https://nodejs.org/dist/v12.22.1/node-v12.22.1.tar.gz"
    source_sha256 = "6023f1f8f03f9780c75e6eca9d372b8411a83757c0389c51baee1c7242afd702"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.22.1_linux_x64_cflinuxfs3_8e413a41.tgz"
    version = "12.22.1"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "e733b24155ff49fb651ea334c1b302c16ea85024192931d840ff958dd196890f"
    source = "https://nodejs.org/dist/v14.16.1/node-v14.16.1.tar.gz"
    source_sha256 = "5f5080427abddde7f22fd2ba77cd2b8a1f86253277a1eec54bc98a202728ce80"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.16.1_linux_x64_cflinuxfs3_e733b241.tgz"
    version = "14.16.1"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "2ebd327ccedbe0b4ac45639679abba835145d916a58f48fd4b17db21ed29e75e"
    source = "https://nodejs.org/dist/v14.17.0/node-v14.17.0.tar.gz"
    source_sha256 = "6114e82d3256136dc85a509d835442fbdf2f8430dcd8bfa7c304097344d06fb7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.17.0_linux_x64_cflinuxfs3_2ebd327c.tgz"
    version = "14.17.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "d240c2853f19e57cfacccf0f1fd7a6c787f519bd6e7507fd38b248d8d71f4ef2"
    source = "https://nodejs.org/dist/v15.13.0/node-v15.13.0.tar.gz"
    source_sha256 = "96926e5b8f2f3ea805596448f01b16115882f3a594e2e999dc7349f80b3ec1f8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.13.0_linux_x64_cflinuxfs3_d240c285.tgz"
    version = "15.13.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "306ae27c61ae7b017f48f5f79ec884a9283ab3e488497b7490ed3d0716d86f59"
    source = "https://nodejs.org/dist/v15.14.0/node-v15.14.0.tar.gz"
    source_sha256 = "f3a35c1b29b58846575085fdee7774d78b75ff4cf1e52572afce7f38685b159a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.14.0_linux_x64_cflinuxfs3_306ae27c.tgz"
    version = "15.14.0"

  [[metadata.dependencies]]
    deprecation_date = "2024-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "aebbbe594a3dece9121dc91999e94efb9e617f99aaeb7cc656d2937a579463ea"
    source = "https://nodejs.org/dist/v16.1.0/node-v16.1.0.tar.gz"
    source_sha256 = "cdc229fff0e18ff9ca29c057691ff29da7bee8b7107b72d8181bdb5c3eeaba00"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_16.1.0_linux_x64_cflinuxfs3_aebbbe59.tgz"
    version = "16.1.0"

  [[metadata.dependencies]]
    deprecation_date = "2024-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "ca6c2deff4fa1ed0d7f9d626c4d1e6bb1d11a387895438601e533e67b6dc8c67"
    source = "https://nodejs.org/dist/v16.2.0/node-v16.2.0.tar.gz"
    source_sha256 = "5d093d6b203159aa3288a1d51495d2faf11550f0755d04015161a529a065b12a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_16.2.0_linux_x64_cflinuxfs3_ca6c2def.tgz"
    version = "16.2.0"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-04-30T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "14.x.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
