api = "0.2"

[buildpack]
  id = "paketo-buildpacks/node-engine"
  name = "Paketo Node Engine Buildpack"
  homepage = "https://github.com/paketo-buildpacks/node-engine"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    node = "14.*.*"

  [[metadata.dependencies]]
    deprecation_date = "2021-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "bd46820b5b4f078e41d59a4a38cc15bfe10d1a5d78ecec15d5e915c9ae9778fe"
    source = "https://nodejs.org/dist/v10.23.2/node-v10.23.2.tar.gz"
    source_sha256 = "b94af8e98b01e1113dd4dc9e2cf8d39446ef7045503552d02f65c58e645ef1b0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_10.23.2_linux_x64_cflinuxfs3_bd46820b.tgz"
    version = "10.23.2"

  [[metadata.dependencies]]
    deprecation_date = "2021-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "82e375d32ac721deea1a3a917d185e601138f64ba2e708f5a83f36407a438410"
    source = "https://nodejs.org/dist/v10.23.3/node-v10.23.3.tar.gz"
    source_sha256 = "517db39eefccb03cb9ec1de67ddc917be943a755b290bff309b2e4b1bd78ffaf"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_10.23.3_linux_x64_cflinuxfs3_82e375d3.tgz"
    version = "10.23.3"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "7fde300a90f69e2c42e88e7bc42e1259b9f715567f3685f3a62000818d8f670e"
    source = "https://nodejs.org/dist/v12.20.1/node-v12.20.1.tar.gz"
    source_sha256 = "5318a5db1484050430371b77dece281a5b078a14e6962e105aa5790bdb3c3bed"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.20.1_linux_x64_cflinuxfs3_7fde300a.tgz"
    version = "12.20.1"

  [[metadata.dependencies]]
    deprecation_date = "2022-04-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "47b0f000242208f9a6229b20cdd98d2271dfea439c4d427d38b58131ff5275df"
    source = "https://nodejs.org/dist/v12.20.2/node-v12.20.2.tar.gz"
    source_sha256 = "47869f9857d40f2ecb42be6c776a8794f4664fb3fb2fdbeb3caad00dc0a36a1f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_12.20.2_linux_x64_cflinuxfs3_47b0f000.tgz"
    version = "12.20.2"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "dd5ea9ba4a072f961fadb6e5935ffa5e11c836f070790cd1b5a5f5dfeb8fc8c3"
    source = "https://nodejs.org/dist/v14.15.4/node-v14.15.4.tar.gz"
    source_sha256 = "8610d81b2d4afc3a79afbe6209d510125131c45cae22cac63bb767dcfec1cbf0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.15.4_linux_x64_cflinuxfs3_dd5ea9ba.tgz"
    version = "14.15.4"

  [[metadata.dependencies]]
    deprecation_date = "2023-04-30T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "63a8a4d43c325856c2e4673b30dc44e8ea973a5a4f21ed616fa7ee2c31cfe7f4"
    source = "https://nodejs.org/dist/v14.15.5/node-v14.15.5.tar.gz"
    source_sha256 = "043f39bb43ecaca699a21a8bd65d064ef53b48bf2cc6acaddb5ee0f4227e4d2a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_14.15.5_linux_x64_cflinuxfs3_63a8a4d4.tgz"
    version = "14.15.5"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "ec63bb7e1d38b401f6fc22582b3881863f677f29d5cb67971bc78f615e48d5ed"
    source = "https://nodejs.org/dist/v15.8.0/node-v15.8.0.tar.gz"
    source_sha256 = "e08c8778a6b767cd0d2ab4613946d1616c3d4054dead08b04f705d607c84510f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.8.0_linux_x64_cflinuxfs3_ec63bb7e.tgz"
    version = "15.8.0"

  [[metadata.dependencies]]
    deprecation_date = "2021-06-01T00:00:00Z"
    id = "node"
    name = "Node Engine"
    sha256 = "737c1f6c0cbb64ce2d663e3e6e1c41fee6d415aa7b1e8bbb5695632ce6576378"
    source = "https://nodejs.org/dist/v15.9.0/node-v15.9.0.tar.gz"
    source_sha256 = "5f41f4d15d7d592b170145cd994c9d7986536bb28ec151046da0632bd30e33bc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/node/node_15.9.0_linux_x64_cflinuxfs3_737c1f6c.tgz"
    version = "15.9.0"

  [[metadata.dependency_deprecation_dates]]
    date = 2021-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "10.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2022-04-01T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "12.x.x"

  [[metadata.dependency_deprecation_dates]]
    date = 2023-04-30T00:00:00Z
    link = "https://github.com/nodejs/Release"
    name = "node"
    version_line = "14.x.x"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
